config/routes.rb
Rails.application.routes.draw do

  resources :distances

  resources :roles

  resources :bookings

  resources :places

  resources :vehicles

  resources :vehicle_types

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  match '/about-us', to: "dashboard#about_us", via: :get
  match '/contact', to: "dashboard#contact", via: :get
  match '/booking', to: "dashboard#booking", via: :get
  devise_for :users

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :from_place, class_name: "Place"
  belongs_to :to_place, class_name: "Place"
  belongs_to :distance
  validates :from_date, :uniqueness => {:scope => :vehicle_id, :message => " The Vehicle is not available today , come tomorrow" }

  before_create :set_distance_id

  def set_distance_id
    distance = Distance.where("start_place_id = #{from_place_id} OR start_place_id = #{to_place_id}").where("end_place_id = #{from_place_id} OR end_place_id = #{to_place_id}").first
    self.distance_id = distance.id
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  load_and_authorize_resource
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        UserMailer.confirmation_email(current_user, @booking).deliver_now
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:from_place_id, :to_place_id, :from_date, :to_date, :vehicle_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_place %><br>
    <%= f.select(:from_place_id, Place.all.collect {|p| [p.name, p.id]}, :prompt => 'Select')%>
  </div>
  <div class="field">
    <%= f.label :to_place %><br>
    <%= f.select(:to_place_id, Place.all.collect {|p| [p.name, p.id]}, :prompt => 'Select')%>
  </div>
  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.date_select :to_date %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.select(:vehicle_id, Vehicle.all.collect {|v| [v.name, v.id]}, :prompt => 'Select')%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>From place</th>
      <th>To place</th>
      <th>From date</th>
      <th>To date</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.from_place.place_name %></td>
        <td><%= booking.to_place.place_name %></td>
        <td><%= booking.from_date %></td>
        <td><%= booking.to_date %></td>
        <td><%= booking.vehicle.vehicle_name %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From place:</strong>
  <%= @booking.from_place.place_name %>
</p>

<p>
  <strong>To place:</strong>
  <%= @booking.to_place.place_name %>
</p>

<p>
  <strong>From date:</strong>
  <%= @booking.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @booking.to_date %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @booking.vehicle.vehicle_name %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>