config/routes.rb
Rails.application.routes.draw do

  resources :distances

  resources :roles

  resources :bookings

  resources :places

  resources :vehicles

  resources :vehicle_types

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  match '/about-us', to: "dashboard#about_us", via: :get
  match '/contact', to: "dashboard#contact", via: :get
  match '/booking', to: "dashboard#booking", via: :get
  devise_for :users

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :vehicle_type

  def vehicle_name
    name
  end
end

app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base
  has_many :vehicles

  def type
    name
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  load_and_authorize_resource
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :vehicle_type_id, :count, :fare)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for @vehicle, :html => { :class => "form-horizontal vehicle" } do |f| %>

    <% if @vehicle.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @vehicle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@vehicle[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :vehicle_type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :vehicle_type_id, VehicleType.all.collect {|v| [v.name, v.id]}, {}, {:class => 'form-control'} %>
    </div>
    <%= error_span(@vehicle[:vehicle_type_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :fare, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :fare, :class => 'form-control' %>
    </div>
    <%= error_span(@vehicle[:fare]) %>
  </div>
  <div class="control-group">
    <%= f.label :count, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :count, :class => 'form-control' %>
    </div>
    <%= error_span(@vehicle[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            vehicles_path, :class => 'btn btn-default' %>

<% end %>

app/views/vehicles/edit.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/index.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:vehicle_type_id) %></th>
      <th><%= model_class.human_attribute_name(:count) %></th>
      <th><%= model_class.human_attribute_name(:fare) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= link_to vehicle.id, vehicle_path(vehicle) %></td>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.vehicle_type.type %></td>
        <td><%= vehicle.count%></td>
        <td><%= vehicle.fare%></td>
        <td><%= vehicle.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vehicle_path(vehicle), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vehicle_path(vehicle),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vehicle_path,
            :class => 'btn btn-primary' %>

app/views/vehicles/new.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vehicles/show.html.erb
<%- model_class = Vehicle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @vehicle.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vehicle_type_id) %>:</strong></dt>
  <dd><%= @vehicle.vehicle_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:count) %>:</strong></dt>
  <dd><%= @vehicle.count %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              vehicles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vehicle_path(@vehicle), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vehicle_path(@vehicle),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>