config/routes.rb
Rails.application.routes.draw do

  resources :distances

  resources :roles

  resources :bookings

  resources :places

  resources :vehicles

  resources :vehicle_types

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  match '/about-us', to: "dashboard#about_us", via: :get
  match '/contact', to: "dashboard#contact", via: :get
  match '/booking', to: "dashboard#booking", via: :get
  devise_for :users

end

app/models/distance.rb
class Distance < ActiveRecord::Base
  belongs_to :start_place, class_name: "Place"
  belongs_to :end_place, class_name: "Place"
  has_many :bookings

  def place_names
    place.name
  end

  def place_namee
    place.name
  end
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  before_action :set_distance, only: [:show, :edit, :update, :destroy]

  # GET /distances
  # GET /distances.json
  def index
    @distances = Distance.all
  end

  # GET /distances/1
  # GET /distances/1.json
  def show
  end

  # GET /distances/new
  def new
    @distance = Distance.new
  end

  # GET /distances/1/edit
  def edit
  end

  # POST /distances
  # POST /distances.json
  def create
    @distance = Distance.new(distance_params)

    respond_to do |format|
      if @distance.save
        format.html { redirect_to @distance, notice: 'Distance was successfully created.' }
        format.json { render :show, status: :created, location: @distance }
      else
        format.html { render :new }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distances/1
  # PATCH/PUT /distances/1.json
  def update
    respond_to do |format|
      if @distance.update(distance_params)
        format.html { redirect_to @distance, notice: 'Distance was successfully updated.' }
        format.json { render :show, status: :ok, location: @distance }
      else
        format.html { render :edit }
        format.json { render json: @distance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distances/1
  # DELETE /distances/1.json
  def destroy
    @distance.destroy
    respond_to do |format|
      format.html { redirect_to distances_url, notice: 'Distance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distance
      @distance = Distance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distance_params
      params.require(:distance).permit(:start_place_id, :end_place_id, :kilometer)
    end
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/views/distances/_form.html.erb
<%= form_for(@distance) do |f| %>
  <% if @distance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distance.errors.count, "error") %> prohibited this distance from being saved:</h2>

      <ul>
      <% @distance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_place_id %><br>
    <%= f.select :start_place_id, Place.all.collect {|p| [p.name, p.id]}, {} %>
  </div>
  <div class="field">
    <%= f.label :end_place_id %><br>
    <%= f.select :end_place_id, Place.all.collect {|p| [p.name, p.id]}, {} %>
  </div>
  <div class="field">
    <%= f.label :kilometer %><br>
    <%= f.number_field :kilometer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/distances/edit.html.erb
<h1>Editing Distance</h1>

<%= render 'form' %>

<%= link_to 'Show', @distance %> |
<%= link_to 'Back', distances_path %>

app/views/distances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Distances</h1>

<table>
  <thead>
    <tr>
      <th>Start place</th>
      <th>End place</th>
      <th>Kilometer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distances.each do |distance| %>
      <tr>
        <td><%= distance.start_place.place_name %></td>
        <td><%= distance.end_place.place_name %></td>
        <td><%= distance.kilometer %></td>
        <td><%= link_to 'Show', distance %></td>
        <td><%= link_to 'Edit', edit_distance_path(distance) %></td>
        <td><%= link_to 'Destroy', distance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distance', new_distance_path %>

app/views/distances/new.html.erb
<h1>New Distance</h1>

<%= render 'form' %>

<%= link_to 'Back', distances_path %>

app/views/distances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start place:</strong>
  <%= @distance.start_place.place_name %>
</p>

<p>
  <strong>End place:</strong>
  <%= @distance.end_place.place_name %>
</p>

<p>
  <strong>Kilometer:</strong>
  <%= @distance.kilometer %>
</p>

<%= link_to 'Edit', edit_distance_path(@distance) %> |
<%= link_to 'Back', distances_path %>